version: "3"
services:
  spring_boot:
    build: ./SpringBoot
    image: server_security/spring_boot
    ports:
      - ${SPRINGBOOT_PORT}:8888
    volumes:
      - ./SpringBoot:/usr/src/app
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mariadb
  flask:
    build: ./Flask
    image: server_security/flask
    ports:
      - ${FLASK_PORT}:5000
    volumes:
      - ./Flask:/usr/src/app
    environment:
      - TZ=Asia/Seoul
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    depends_on:
      - mariadb
  mariadb:
    build: ./MariaDB
    image: server_security/mariadb
    volumes:
      - ./MariaDB/data:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306
    environment:
      - TZ=Asia/Seoul
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    restart: always
