server:
    port: 8080

spring:
    application:
      name: spring

    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://mariadb:3306/dca_db
      username: dca_user
      password: dca
